FROM supabase/realtime:latest

COPY ./bash_scripts/wait-for-db.sh /usr/local/bin/wait-for-db.sh
COPY ./runtime.exs /app/releases/2.41.15/runtime.exs

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    chmod +x /usr/local/bin/wait-for-db.sh

ENTRYPOINT ["/usr/local/bin/wait-for-db.sh"]

CMD ["/app/bin/realtime", "start"]